### ISSUE TITLE
adding colab badges

### ISSUE THREAD

**Issue by KBodolai** [ESA-PhiLab/OST_Notebooks#5]
Hi,

Given that colab is a nice environment for people to first test the tools, I though it would reduce friction and help people to add a colab badge pointing to the notebooks. Let me know if that's something you'd be interested in, I'm happy to do it myself and submit a PR.

Cheers,
K.

**Comment by BuddyVolly** [comment]
That would be awesome! Thanks

**Comment by 12rambau** [comment]
Note that some Ipython display functionalities are not available on Google Colab, so maybe in addition, we could consider creating a binder (pure Jupyter instance)

**Comment by KBodolai** [comment]
Good, will make a PR with that later today.

About binder, I think it's a good idea, but in mybinder.org RAM will be between 1 and 2 GB, which would limit trying it out. 

What Ipython functionalities are not working currently?

**Comment by 12rambau** [comment]
nothing specific I just wanted to mention it here in case an issue was rising afterward.

**Comment by BuddyVolly** [comment]
As a comment, I do not think we have issues with IPython widgets, as they are not used in the OST notebooks.
